name: labjack
channels:
- conda-forge
dependencies:
- python=3.6
- psychopy
- ipython
- liblsl
- pip
- pip:
  - psychtoolbox
  - pygame
  - pyo
  - pyparallel; platform_system != "Windows"
  - SoundFile; platform_system == "Windows"
  - websocket_client
  - LabJackPython
  - pylsl
